### ISSUE TITLE
How to filter out some folder in the project ?

### ISSUE THREAD

**Issue by pipiche38** [theahura/pytype-action#2]
I'm wondering how to exclude some folder of the project

**Comment by pselamy** [comment]
How did you achieve this? The following doesn't work for me:

```
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pytype checker
      uses: theahura/pytype-action@v1.6
      with:
        args: -d "import-error,module-attr,pyi-error" --exclude "/vendor/"
```
